version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: prismaapi-app
    ports:
      - "3000:3000"
    volumes:
        - .:/home/node/app
  db:
    image: postgres:11
    container_name: prismaapi-db
    restart: always
    ports:
      - "5555:5432"
    tty: true
    volumes:
        - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: prismaapi